name: ImageRep
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - numpy
  - torchvision
  - pytorch-cuda=11.6
  - pytorch=1.13.1
  - pip

  - pip:
      - matplotlib
      - opencv-python
      - wandb
      - tqdm
      - pydantic
      - pytorch-lightning






